parameters:
    imatic_view.menu.main.class: Imatic\Bundle\ViewBundle\Menu\MainMenuBuilder

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Imatic\Bundle\ViewBundle\:
        resource: '../../*'
        exclude: '../../{Tests,vendor}'

    # Menu
    Imatic\Bundle\ViewBundle\Menu\ContainerProvider:
        tags:
          - { name: knp_menu.provider }

    imatic_view.menu.main:
        class: '%imatic_view.menu.main.class%'
        public: true
        tags:
            - { name: imatic_view.menu, alias: imatic.main }
            - { name: imatic_view.menu, alias: imatic.main_side, method: getSideMenu }

    Imatic\Bundle\ViewBundle\Menu\DemoMenuBuilder:
        public: true
        tags:
            - { name: imatic_view.menu, alias: imatic.demo }
            - { name: imatic_view.menu, alias: imatic.demo_normal, method: getNormalMenu }
            - { name: imatic_view.menu, alias: imatic.demo_sub, method: getSubMenu }

    # Twig runtime
    Imatic\Bundle\ViewBundle\Twig\Runtime\FormatRuntime:
        tags:
            - { name: twig.runtime }

    Imatic\Bundle\ViewBundle\Twig\Runtime\MenuRuntime:
        arguments:
            $renderer: '@knp_menu.renderer.twig'
        tags:
            - { name: twig.runtime }

    # Formatters
    Imatic\Bundle\ViewBundle\Templating\Helper\Format\IntlFormatter:
        tags:
            - { name: imatic_view.formatter, alias: time }
            - { name: imatic_view.formatter, alias: date }
            - { name: imatic_view.formatter, alias: datetime }
            - { name: imatic_view.formatter, alias: number }

    Imatic\Bundle\ViewBundle\Templating\Helper\Format\CommonFormatter:
        tags:
            - { name: imatic_view.formatter, alias: url, is_safe: html }
            - { name: imatic_view.formatter, alias: phone, is_safe: html }
            - { name: imatic_view.formatter, alias: email, is_safe: html }
            - { name: imatic_view.formatter, alias: text, is_safe: html }
            - { name: imatic_view.formatter, alias: html, is_safe: html }
            - { name: imatic_view.formatter, alias: boolean, is_safe: html }
            - { name: imatic_view.formatter, alias: link, is_safe: html }
            - { name: imatic_view.formatter, alias: filesize }
            - { name: imatic_view.formatter, alias: translatable }

    # Event listners
    Imatic\Bundle\ViewBundle\EventListener\KernelSubscriber:
        arguments:
            $debug: '%kernel.debug%'
