parameters:
    imatic_view.menu.main.class: Imatic\Bundle\ViewBundle\Menu\MainMenuBuilder

services:
    # Menu
    imatic_view.menu.provider_container:
        class: Imatic\Bundle\ViewBundle\Menu\ContainerProvider
        arguments:
          - @service_container
        tags:
          - { name: knp_menu.provider }

    imatic_view.menu.factory:
        class: Imatic\Bundle\ViewBundle\Menu\Factory
        arguments: [ @knp_menu.factory ]

    imatic_view.menu.helper:
        class: Imatic\Bundle\ViewBundle\Menu\Helper
        arguments: [ @translator, @?security.context ]

    imatic_view.menu.main:
        class: %imatic_view.menu.main.class%
        arguments: [ @imatic_view.menu.provider_container ]
        tags:
            - { name: imatic_view.menu, alias: imatic.main }
            - { name: imatic_view.menu, alias: imatic.main_side, method: getSideMenu }

    imatic_view.menu.demo:
        class: Imatic\Bundle\ViewBundle\Menu\DemoMenuBuilder
        tags:
            - { name: imatic_view.menu, alias: imatic.demo }
            - { name: imatic_view.menu, alias: imatic.demo_sub, method: getMenuSub }

    # Twig extensions
    imatic_view.twig.extension.debug:
        class:        Twig_Extension_Debug
        tags:
            - { name: 'twig.extension' }

    imatic_view.twig.extension.application:
        class:        Imatic\Bundle\ViewBundle\Twig\Extension\ApplicationExtension
        arguments:    [ @service_container ]
        tags:
            - { name: 'twig.extension' }

    imatic_view.twig.extension.menu:
        class:        Imatic\Bundle\ViewBundle\Twig\Extension\MenuExtension
        arguments:    [ @imatic_view.menu.factory, @knp_menu.renderer.twig ]
        tags:
            - { name: 'twig.extension' }

    imatic_view.twig.extension.configuration:
        class:        Imatic\Bundle\ViewBundle\Twig\Extension\ConfigurationExtension
        arguments:    [ @service_container ]
        tags:
            - { name: 'twig.extension' }

    imatic_view.twig.extension.string:
        class:        Imatic\Bundle\ViewBundle\Twig\Extension\StringExtension
        tags:
            - { name: 'twig.extension' }

    imatic_view.twig.extension.html:
        class:        Imatic\Bundle\ViewBundle\Twig\Extension\HtmlExtension
        tags:
            - { name: 'twig.extension' }

    # Twig loaders
    imatic_view.twig.loader.remote:
        class:        Imatic\Bundle\ViewBundle\Twig\Loader\RemoteLoader
        arguments:
            - @service_container
        tags:
            - { name: 'twig.loader' }
