language: php

php: 7.1

addons:
    apt:
        packages:
            - graphviz

before_script:
    - phpenv config-rm xdebug.ini
    - cp ./Tests/Fixtures/TestProject/config/parameters.yml.dist ./Tests/Fixtures/TestProject/config/parameters.yml
    - composer install

script:
    - make test
