#!/usr/bin/env php
<?php
require __DIR__ . '/../../bootstrap.php';
umask(0007);

use Imatic\Testing\Test\Console;

$console = new Console('Imatic\Bundle\ViewBundle\Tests\Fixtures\TestProject\TestKernel');
$console->run();
